// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlite

import ()

type Stock struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	Status         int32  `json:"status"`
	ProductType    int32  `json:"product_type"`
	Type           int32  `json:"type"`
	Supplier       string `json:"supplier"`
	Model          string `json:"model"`
	Unit           string `json:"unit"`
	Price          int32  `json:"price"`
	BatchNoIn      string `json:"batch_no_in"`
	WayIn          string `json:"way_in"`
	Location       string `json:"location"`
	BatchNoProduce string `json:"batch_no_produce"`
	ProduceDate    string `json:"produce_date"`
	StockDate      string `json:"stock_date"`
	StockNum       int32  `json:"stock_num"`
	CurrentNum     int32  `json:"current_num"`
	Value          int32  `json:"value"`
}

type StockApplication struct {
	ID              int32  `json:"id"`
	ApplicationDate string `json:"application_date"`
	BatchNoIn       string `json:"batch_no_in"`
	Status          int32  `json:"status"`
	ApplicationUser string `json:"application_user"`
	ApproveUser     string `json:"approve_user"`
	ApproveDate     string `json:"approve_date"`
	CreateDate      string `json:"create_date"`
}

type StockOutApplication struct {
	ID              int32  `json:"id"`
	Stockids        string `json:"stockids"`
	Status          int32  `json:"status"`
	ApplicationUser string `json:"application_user"`
	ApproveUser     string `json:"approve_user"`
	CreateDate      string `json:"create_date"`
}
