// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlite

import ()

type Stock struct {
	ID             int32
	Name           string
	ProductType    int32
	Type           int32
	Supplier       string
	Model          string
	Unit           string
	Price          int32
	BatchNoIn      string
	WayIn          string
	Location       string
	BatchNoProduce string
	ProduceDate    string
	StockDate      string
	StockNum       int32
	CurrentNum     int32
	Value          int32
}
