// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlite

import ()

type Stock struct {
	ID             int64
	Name           string
	ProductType    int64
	Type           int64
	Supplier       string
	Model          string
	Unit           string
	Price          int64
	BatchNoIn      string
	WayIn          string
	Location       string
	BatchNoProduce string
	ProduceDate    string
	StockDate      string
	StockNum       int64
	CurrentNum     int64
	Value          int64
}
